spring:
  datasource:
    url: jdbc:mysql://sh-cynosdbmysql-grp-c7ar96e0.sql.tencentcdb.com:24057/cms
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: yanghi
    password: YANGyihi2001
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  # 配置redis
  redis:
    host: 127.0.0.1 #Redis服务器地址
    port: 6379 #Redis服务器连接端口
    password: 410327
    database: 0   #Redis数据库索引（默认为0）
    timeout: 1800000  #连接超时时间（毫秒）
    lettuce:
      pool:
        max-active: 20  #连接池最大连接数（使用负值表示没有限制）
        max-idle: 5  #连接池中的最大空闲连接
        min-idle: 0  #连接池中的最小空闲连接
        max-wait: -1 #最大阻塞等待时间(负数表示没限制)
  cos:
    accessKey: AKIDbGtLdrshP1cLyNXTCk15wd7QWVP4pNip
    secretKey: 30qTr0tY1KQHvJWZO0NXVDkDTVJsBGKY
    bucket: ap-nanjing
    bucketName: yanghi-save-1312993591
    path: https://yanghi-save-1312993591.cos.ap-nanjing.myqcloud.com
    prefix: /img/

#配置mybatis
mybatis-plus:
  #启动bean实体类简化写法
  type-aliases-package: com.example.sstest.bean
  mapper-locations: classpath:mapper/*.xml
  #  config-location: classpath:mybatis/mybatis-config.xml
  #注意有了configuration配置，就不能配置config-location了
  configuration: #指定mybatis的全局配置
    # 配置驼峰命名 自动注入
    map-underscore-to-camel-case: true
  global-config:
    banner: false
    db-config:
      logic-delete-field: delFlag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
server:
  port: 9999

logging:
  level:
    com.example.sstest: debug
